config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :foods do
     resource :favorites, only: [:create, :destroy]
    resources :food_comments, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, optional: true #投稿時にuserのnillを許可
  validates :title, presence: true
  validates :body, presence: true

  has_many :food_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists? #引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  end
end

app/models/food_comment.rb
class FoodComment < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :food_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true #同じ名前は一人のみ
  validates :introduction, length: {maximum: 50}

end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource) #ログイン後遷移先
    user_path(current_user)
  end

  def after_sign_out_path_for(resource) #ログアウト後遷移先
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @food = Food.find(params[:food_id])
    favorite = @food.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer #遷移元のURLを取得してリダイレクト
  end

  def destroy
    @food = Food.find(params[:food_id])
    favorite = @food.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer #遷移元のURLを取得してリダイレクト
  end

end

app/controllers/food_comments_controller.rb
class FoodCommentsController < ApplicationController

  def create
    @food = Food.find(params[:food_id])
    @food_comment = FoodComment.new(food_comment_params)
    @food_comment.user_id = current_user.id
    @food_comment.food_id = @food.id
    @food_comment.save
    redirect_to food_path(params[:food_id])

  end

  def destroy
    @food = Food.find(params[:food_id])
    food_comment = @food.food_comments.find(params[:id])
    food_comment.destroy
    redirect_to food_path(params[:food_id])
  end

  private

  def food_comment_params
    params.require(:food_comment).permit(:comment)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user! #ユーザーがログインしているかどうか確認
  before_action :ensure_user, only: [:edit, :update, :destroy] #投稿したユーザーのみ編集、削除可能

  def index
    @foods = Food.all
    @food = Food.new
    @user = current_user
  end

  def show
    @food = Food.find(params[:id])
     @food_new = Food.new
    @food_comment = FoodComment.new
    @user = current_user

  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id #どのユーザーが投稿したのか紐付け
    if @food.save #バリデーションの追加
       flash[:notice] = '投稿が完了しました！'
      redirect_to foods_path
    else
      @foods = Food.all
      render :index
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to foods_path
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    food = Food.find(params[:id])
    if food.update(food_params)
    flash[:notice] = '更新が完了しました！'
    redirect_to foods_path(food)
    else
      render :edit
    end
  end

  private
  def food_params
    params.require(:food).permit(:title, :body)
  end

  def ensure_user
    @foods = current_user.foods
    @food = @foods.find_by(id: params[:id])
    redirect_to foods_path unless @food
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy] #本人のみ編集、削除可能

  def index
    @users = User.all
    @food_new = Food.new
  end

  def show
    @user = User.find(params[:id])
    @food_new = Food.new
    @foods = @user.foods
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = '更新が完了しました！'
       redirect_to user_path(current_user)
    else
       render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/food_comments_helper.rb
module FoodCommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if food.favorited_by?(current_user) %>
 <p>
  <%= link_to food_favorites_path(food), method: :delete do %>
   ♥<%= food.favorites.count %>
  <% end %>
 </p>
<% else %>
 <p>
  <%= link_to food_favorites_path(food), method: :post do %>
   ♡<%= food.favorites.count %>
  <% end %>
 </p>
<% end %>

app/views/foods/_newfood.html.erb
<h1 class="mt-3">New post</h1>
<%= form_with model: food_new, local:true do |f| %>
<h4>タイトル</h4>
<%= f.text_field :title %>
<h4>本文</h4>
<%= f.text_area :body %>
<%= f.submit "投稿する", class: 'btn btn-primary' %>
<% end %>

app/views/foods/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  		<h1>Editing Food</h1>

  		<%= form_with model:@food, local:true do |f| %>
      <h4>タイトル</h4>
      <%= f.text_field :title %>
      <h4>本文</h4>
       <%= f.text_area :body %>
      <%= f.submit "保存" %>
      <% end %>

  		<%= link_to "Show",food_path(@food.id)%> |
  		<%= link_to "Back",foods_path %>

   </div>
  </div>
 </div>

app/views/foods/index.html.erb
<% if @food.errors.any? %> <!--エラーメッセージ-->
  <%= @food.errors.count %>件のエラーが発生しました
  <% @food.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


 <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%= render 'users/userinfo' %>
        <%= render 'foods/newfood', food_new: @food %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h1>Healthy Foods</h1>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>本文</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @foods.each do |food| %>
            <tr>
              <td>
                <%= link_to user_path(food.user) do %>
                <%= attachment_image_tag food.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td>
                <%= link_to food_path(food.id) do %>
                <p><%= food.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= food.body %></p>
              </td>
              <td class="favorite-btn"><%= render "favorites/favorite-btn", food: food %></td>
              <td>コメント数: <%= food.food_comments.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>

app/views/foods/new.html.erb
<h1>新規投稿</h1>

<% if @food.errors.any? %>
 <%= @food.errors.count %>件のエラーが発生しました。
 <% @food.errors.full_messages.each do |message| %>
  <%= message %>
 <% end %>
<% end %>

<%= form_with model:@food, local:true do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>

<% end %>

app/views/foods/show.html.erb
<div class="container">
    <div class="row">

      <div class="col-md-3">

        <%= render 'users/userinfo', current_user: @user %>

        <%= render 'foods/newfood', food_new: @food_new %>

      </div>

      <div class="col-md-8 offset-md-1">
        <h1>Healthy Food detail</h1>
        <table class="table">
          <tbody>
            <tr>
              <td><%= attachment_image_tag @food.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
              <br><%= link_to user_path(@user) do %><%= @user.name %><% end %>
              </td>
              <td><%= link_to @food.title, food_path(@food) %></td>
              <td><%= @food.body %></td>
              <td class="favorite-btn"><%= render "favorites/favorite-btn", food: @food %></td>
              <td>コメント数: <%= @food.food_comments.count %></td>
              <% if current_user == @food.user %>
              <td>
                <%=link_to "Edit",edit_food_path(@food.id), class: "btn btn-sm btn-success" %>
              </td>
              <td>
                <%=link_to "Destroy",food_path(@food.id), class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか?" %>
              </td>
              <% else %>
      　　　　　　　<td></td>
      　　　　　　　<td></td>
              <% end %>

            </tr>
          </tbody>
        </table>

        <h2>Comment</h2>
        <table>
        <% @food.food_comments.each do |food_comment| %>
        <% food_comment_user = food_comment.user %>
        <tr>
  	    <td>
  		<%= link_to user_path(food_comment_user), class: "user_#{food_comment_user.id}" do %>
    		<%= attachment_image_tag food_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
    		<%= food_comment_user.name %>
  		<% end %>
  	    </td>
  	    <td><%= food_comment.comment %></td>
  	    <% if current_user == food_comment_user %>
    	<td><%= link_to 'Destroy', food_food_comment_path(food_comment.food_id, food_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
  	    <% end %>
        </tr>
        <% end %>
        </table>

        <%= form_with model:[@food,@food_comment] do |f| %>
         <%= f.text_area :comment %>
         <%= f.submit '送信', class: 'btn btn-primary' %>
        <% end %>

      </div>

    </div>
  </div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto col-11 co-sm-10 col-lg-8 col-xl-6">
      <h2>
       <strong>Healthy Food Life</strong>
       は、様々なユーザーの声を聞いて自分に合う健康食品を知るためのサイトです。
       <br>
       自分が使用した感想や体感した効果を誰かと共有したいときにも活用できます。
     </h2>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class-"row">
      <div class="mx-auto col-11 co-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to<br>
         <strong>Healthy Food Life</strong>
          !!
        </h1>

        <h1>自分に合った健康食品を<br>
        発見しましょう！</h1>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to"Log in", "/users/sign_in",  class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", "/users/sign_up", class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthyFoodLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-success"> <!--nabar色名、 bg-色名 -->
      <div class="container">
      <a class="navbar-brand" href="/"><span>Healthy Food Life</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'nav-link text-light' %></li>
          <li><%= link_to ' Users',users_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' Foods',foods_path ,class: 'nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' About',home_about_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'nav-link text-light' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
     </div>
     </nav>
     </header>

    <main>

      <% if flash[:notice] %> <!--サクセス・エラーメッセージの表示-->
        <div class="flash">
          <%= flash[:notice] %>
        </div>
       <% end %>

      <%= yield %>
    </main>

  </body>
</html>

app/views/users/_userinfo.html.erb
<h1>User info</h1>
  <%= attachment_image_tag current_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
<table class="table">
 <tbody>
  <tr></tr>
  <tr>
    <th>ユーザー名</th>
    <th><%= current_user.name %></th>
  </tr>
  <tr>
    <th>プロフィール</th>
    <th><%= current_user.introduction %></th>
    <th></th>
  </tr>
 </tbody>
</table>

<div class="row">
  <p><%= link_to "プロフィール編集", edit_user_path(current_user.id), class: 'btn btn-success' %></p>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :ユーザー名 %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :プロフィール画像 %>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="form-group">
        <%= f.label :プロフィール %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%= render 'users/userinfo' %>
        <%= render 'foods/newfood', food_new: @food_new %>

      </div>

      <div class="col-md-8 offset-md-1">
        <h1>Users</h1>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>ユーザー名</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <p><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %></p>
              </td>
              <td>
                <p><%= user.name %></p>
              </td>
              <td>
                <p><%= link_to"Show",user_path(user.id) %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>

app/views/users/show.html.erb
 <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

       <%= render 'users/userinfo', current_user: @user %>

       <%= render 'foods/newfood', food_new: @food_new %>

      </div>

      <div class="col-md-8 offset-md-1">
        <h1>Healthy foods</h1>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>本文</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @foods.each do |food| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= attachment_image_tag food.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td>
                <%= link_to food_path(food.id) do %>
                <p><%= food.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= food.body %></p>
              </td>
              <td class="favorite-btn"><%= render "favorites/favorite-btn", food: food %></td>
              <td>コメント数: <%= food.food_comments.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>